#!/usr/bin/env ruby

require 'telegram/bot'

token = `cat /etc/bot25/token`.strip
bot_username = '@Giovanni25_bot'

puts "[INFO] Running bot #{$0}..."

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    puts " => #{message.text}"
    if message.text == "/hola"
      bot.api.send_message(chat_id: message.chat.id, text: "Oooh, ¡que pasó!")
    elsif message.text == "/adios"
      bot.api.send_message(chat_id: message.chat.id, text: "Engaa, ¡nos vemos!")
    elsif message.text == "/ip"
      ip = `ip a | grep inet | grep eth1`.split
      bot.api.send_message(chat_id: message.chat.id, text: "Tiene asignada la IP: #{ip[1]}")
    elsif message.text == "/ping"
      ms = `ping 8.8.4.4 -c1`
      bot.api.send_message(chat_id: message.chat.id, text: ms)
    elsif message.text == "/apache"
      estados = `systemctl status apache2 | grep Active`.split
      bot.api.send_message(chat_id: message.chat.id, text: "El estado de Apache es: #{estados[1]}")
    elsif message.text == "/apacheon"
      estados = `systemctl status apache2 | grep Active`.split
      bot.api.send_message(chat_id: message.chat.id, text: "El estado de Apache es: #{estados[1]}")
    end
  end
end
